---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extensions.gardener.cloud:provider-aws:aws-custom-route-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extensions.gardener.cloud:provider-aws:aws-custom-route-controller
subjects:
- kind: ServiceAccount
  name: aws-custom-route-controller
  namespace: kube-system
