apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-load-balancer-controller.webhookService" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    name: webhook-server
    targetPort: 9443
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
