{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aws-load-balancer-controller.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      minAllowed:
        memory: {{ .Values.resources.requests.memory }}
      controlledValues: RequestsOnly
{{- end }}
