{{- if and .Values.global.virtualGarden.enabled ( not .Values.global.virtualGarden.user.name ) ( not .Values.gardener.garden ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- end }}
